-- Richer post-release notes for economic events.
-- Generated by Gemini after an actual value is detected.
-- Stored as a JSONB array of bullet-point notes + metadata.

alter table public.economic_events
  add column if not exists notes jsonb;

-- notes JSON structure:
-- {
--   "bullets": [
--     "Core CPI came in at 3.3% vs 3.2% forecast, signaling persistent inflation",
--     "GBP/USD spiked 45 pips within 2 minutes of the release",
--     "Markets now pricing in higher probability of BOE rate hold at March meeting",
--     "Gold fell $8 as dollar strengthened on the data"
--   ],
--   "keyTakeaway": "Higher-than-expected inflation keeps pressure on BOE, supporting GBP in the short term",
--   "affectedPairs": ["GBP/USD", "EUR/GBP", "GBP/JPY"],
--   "priceAction": "bullish",
--   "generatedAt": "2025-02-18T14:30:00Z"
-- }

comment on column public.economic_events.notes is
  'AI-generated detailed bullet-point notes after event release. Contains bullets array, keyTakeaway, affectedPairs, priceAction, and generatedAt.';
